# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deepak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deepak


  target 'deepakTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'deepak-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deepak-tvOS

  target 'deepak-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
